/*
The MIT License (MIT)
Copyright (c) 2015 Darren Osten
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.03.05 at 06:45:28 PM PST
//

package net.osten.watermap.pct.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * A link to an external resource (Web page, digital photo, video clip, etc) with additional information.
 *
 *
 * <p>
 * Java class for linkType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="linkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "linkType", propOrder = { "text", "type" })
public class LinkType
{

   protected String text;
   protected String type;
   @XmlAttribute(name = "href", required = true)
   @XmlSchemaType(name = "anyURI")
   protected String href;

   /**
    * Gets the value of the href property.
    *
    * @return possible object is {@link String }
    *
    */
   public String getHref()
   {
      return href;
   }

   /**
    * Gets the value of the text property.
    *
    * @return possible object is {@link String }
    *
    */
   public String getText()
   {
      return text;
   }

   /**
    * Gets the value of the type property.
    *
    * @return possible object is {@link String }
    *
    */
   public String getType()
   {
      return type;
   }

   /**
    * Sets the value of the href property.
    *
    * @param value allowed object is {@link String }
    *
    */
   public void setHref(String value)
   {
      this.href = value;
   }

   /**
    * Sets the value of the text property.
    *
    * @param value allowed object is {@link String }
    *
    */
   public void setText(String value)
   {
      this.text = value;
   }

   /**
    * Sets the value of the type property.
    *
    * @param value allowed object is {@link String }
    *
    */
   public void setType(String value)
   {
      this.type = value;
   }

}
