/*
The MIT License (MIT)
Copyright (c) 2015 Darren Osten
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.03.05 at 06:45:28 PM PST
//

package net.osten.watermap.pct.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the net.osten.watermap.pct.xml package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory
{

   private final static QName _Gpx_QNAME = new QName("http://www.topografix.com/GPX/1/1", "gpx");

   /**
    * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.osten.watermap.pct.xml
    *
    */
   public ObjectFactory()
   {}

   /**
    * Create an instance of {@link BoundsType }
    *
    */
   public BoundsType createBoundsType()
   {
      return new BoundsType();
   }

   /**
    * Create an instance of {@link CopyrightType }
    *
    */
   public CopyrightType createCopyrightType()
   {
      return new CopyrightType();
   }

   /**
    * Create an instance of {@link EmailType }
    *
    */
   public EmailType createEmailType()
   {
      return new EmailType();
   }

   /**
    * Create an instance of {@link ExtensionsType }
    *
    */
   public ExtensionsType createExtensionsType()
   {
      return new ExtensionsType();
   }

   /**
    * Create an instance of {@link JAXBElement }{@code <}{@link GpxType }{@code >}
    *
    */
   @XmlElementDecl(namespace = "http://www.topografix.com/GPX/1/1", name = "gpx")
   public JAXBElement<GpxType> createGpx(GpxType value)
   {
      return new JAXBElement<GpxType>(_Gpx_QNAME, GpxType.class, null, value);
   }

   /**
    * Create an instance of {@link GpxType }
    *
    */
   public GpxType createGpxType()
   {
      return new GpxType();
   }

   /**
    * Create an instance of {@link LinkType }
    *
    */
   public LinkType createLinkType()
   {
      return new LinkType();
   }

   /**
    * Create an instance of {@link MetadataType }
    *
    */
   public MetadataType createMetadataType()
   {
      return new MetadataType();
   }

   /**
    * Create an instance of {@link PersonType }
    *
    */
   public PersonType createPersonType()
   {
      return new PersonType();
   }

   /**
    * Create an instance of {@link PtsegType }
    *
    */
   public PtsegType createPtsegType()
   {
      return new PtsegType();
   }

   /**
    * Create an instance of {@link PtType }
    *
    */
   public PtType createPtType()
   {
      return new PtType();
   }

   /**
    * Create an instance of {@link RteType }
    *
    */
   public RteType createRteType()
   {
      return new RteType();
   }

   /**
    * Create an instance of {@link TrksegType }
    *
    */
   public TrksegType createTrksegType()
   {
      return new TrksegType();
   }

   /**
    * Create an instance of {@link TrkType }
    *
    */
   public TrkType createTrkType()
   {
      return new TrkType();
   }

   /**
    * Create an instance of {@link WptType }
    *
    */
   public WptType createWptType()
   {
      return new WptType();
   }

}
