/*
The MIT License (MIT)
Copyright (c) 2015 Darren Osten
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.03.05 at 06:45:28 PM PST
//

package net.osten.watermap.pct.xml;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 *
 * A geographic point with optional elevation and time. Available for use by other schemas.
 *
 *
 * <p>
 * Java class for ptType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ptType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ele" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="lat" use="required" type="{http://www.topografix.com/GPX/1/1}latitudeType" />
 *       &lt;attribute name="lon" use="required" type="{http://www.topografix.com/GPX/1/1}longitudeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ptType", propOrder = { "ele", "time" })
public class PtType
{

   protected BigDecimal ele;
   @XmlSchemaType(name = "dateTime")
   protected XMLGregorianCalendar time;
   @XmlAttribute(name = "lat", required = true)
   protected BigDecimal lat;
   @XmlAttribute(name = "lon", required = true)
   protected BigDecimal lon;

   /**
    * Gets the value of the ele property.
    *
    * @return possible object is {@link BigDecimal }
    *
    */
   public BigDecimal getEle()
   {
      return ele;
   }

   /**
    * Gets the value of the lat property.
    *
    * @return possible object is {@link BigDecimal }
    *
    */
   public BigDecimal getLat()
   {
      return lat;
   }

   /**
    * Gets the value of the lon property.
    *
    * @return possible object is {@link BigDecimal }
    *
    */
   public BigDecimal getLon()
   {
      return lon;
   }

   /**
    * Gets the value of the time property.
    *
    * @return possible object is {@link XMLGregorianCalendar }
    *
    */
   public XMLGregorianCalendar getTime()
   {
      return time;
   }

   /**
    * Sets the value of the ele property.
    *
    * @param value allowed object is {@link BigDecimal }
    *
    */
   public void setEle(BigDecimal value)
   {
      this.ele = value;
   }

   /**
    * Sets the value of the lat property.
    *
    * @param value allowed object is {@link BigDecimal }
    *
    */
   public void setLat(BigDecimal value)
   {
      this.lat = value;
   }

   /**
    * Sets the value of the lon property.
    *
    * @param value allowed object is {@link BigDecimal }
    *
    */
   public void setLon(BigDecimal value)
   {
      this.lon = value;
   }

   /**
    * Sets the value of the time property.
    *
    * @param value allowed object is {@link XMLGregorianCalendar }
    *
    */
   public void setTime(XMLGregorianCalendar value)
   {
      this.time = value;
   }

}
